version: '3.3'
services:

  postgres:
    container_name: postgres_db_connector
    hostname: postgres_db_connector
    image: postgres:13.0
    restart: always
    volumes:
      - .././.cicd/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - db_connector_net
    ports:
      - 5432:5432

  db-connector:
    container_name: backend-db-connector
    build:
      context: ..
      dockerfile: .cicd/Dockerfile.app
      network: db_connector_net
    ports:
      - "8080:8080"
    networks:
      - db_connector_net
    environment:
      DATABASE_HOST: postgres_db_connector
      DATABASE_PORT: 5432
      DATABASE_NAME: db_connections_storage
      DATABASE_SCHEMA: dbconnectionsstorage
      DATABASE_USERNAME: dbconnectionsstorage_user
      DATABASE_PASSWORD: dbconnectionsstorage_user
      LIQUIBASE_USERNAME: dbconnectionsstorage
      LIQUIBASE_PASSWORD: dbconnectionsstorage
volumes:
  db-connector:

networks:
  db_connector_net:
    driver: bridge
    name: db_connector_net