server:
  port: 8080
spring:
  response-starter:
    swagger:
      apiinfo:
        title: Db connector service
        contact:
          name: Boris Kezikov
          email: boris200898@icloud.com
  session:
    jdbc:
      table-name: SPRING_SESSION
    store-type: jdbc
  datasource:
    data: heroku_init.sql
    url: "jdbc:postgresql://${DATABASE_HOST:ec2-34-237-247-76.compute-1.amazonaws.com}:${DATABASE_PORT:5432}/${DATABASE_NAME:d8aen9s893c7dv}?currentSchema=${DATABASE_SCHEMA:public}"
    username: ${DATABASE_USERNAME:qjrfdcsfpwiwzo}
    password: ${DATABASE_PASSWORD:01ab19bc662855a6d69817fc9406c4c0b50d9224590ac4d35364bfde6aed88f1}
    hikari:
      connection-timeout: 50000
      minimum-idle: 10
      maximum-pool-size: 100
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  liquibase:
    change-log: 'classpath:changelog/db.changelog-master.yml'
    user: ${LIQUIBASE_USERNAME:qjrfdcsfpwiwzo}
    password: ${LIQUIBASE_PASSWORD:01ab19bc662855a6d69817fc9406c4c0b50d9224590ac4d35364bfde6aed88f1}
application:
  name: db_connector
  api:
    version: 1.0


