
CREATE USER test1 WITH password 'test1';
CREATE USER test2 WITH password 'test2';

CREATE DATABASE "test_db" WITH OWNER = postgres ENCODING = 'UTF8';

CREATE TABLE test (
    field CHAR(36) NOT NULL,
    id BIGINT NOT NULL,
    CONSTRAINT spring_session_pk PRIMARY KEY (id)
);

GRANT ALL PRIVILEGES ON TABLE  test TO test1;
GRANT ALL PRIVILEGES ON TABLE  test TO test2;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO test1;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT USAGE ON SEQUENCES TO test1;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO test1;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO test2;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT USAGE ON SEQUENCES TO test2;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO test2;

