CREATE USER adminer WITH password 'adminer';

CREATE DATABASE "test_db" WITH OWNER = postgres ENCODING = 'UTF8';
\connect "test_db";

CREATE USER test1 WITH password 'test1';
CREATE USER test2 WITH password 'test2';

CREATE SCHEMA test_schema AUTHORIZATION adminer;

GRANT USAGE ON SCHEMA test_schema TO test1;
GRANT USAGE ON SCHEMA test_schema TO test2;

ALTER DEFAULT PRIVILEGES FOR USER adminer IN SCHEMA test_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO test1;
ALTER DEFAULT PRIVILEGES FOR USER adminer IN SCHEMA test_schema GRANT USAGE ON SEQUENCES TO test1;
ALTER DEFAULT PRIVILEGES FOR USER adminer IN SCHEMA test_schema GRANT EXECUTE ON FUNCTIONS TO test1;
ALTER DEFAULT PRIVILEGES FOR USER adminer IN SCHEMA test_schema GRANT SELECT ON TABLES TO test1;

CREATE TABLE test_schema.TEST_TABLE
(
    field CHAR(36) NOT NULL,
    id    BIGINT   NOT NULL,
    age     INT,
    CONSTRAINT spring_session_pk PRIMARY KEY (id)
);
GRANT ALL PRIVILEGES ON TABLE test_schema.TEST_TABLE TO test1;
GRANT ALL PRIVILEGES ON TABLE test_schema.TEST_TABLE TO test2;
GRANT ALL PRIVILEGES ON TABLE test_schema.TEST_TABLE TO adminer;

